import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How LoL AI Coach collects, uses, and protects your data.",
};

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="font-display text-4xl font-bold text-text">Privacy Policy</h1>
      <p className="mt-3 text-sm text-text-muted">Last updated: June 2026</p>

      <div className="mt-10 space-y-10 text-sm leading-relaxed text-text-muted">
        <section>
          <h2 className="mb-3 font-display text-xl font-semibold text-text">
            Information We Collect
          </h2>
          <p>
            When you create an account, we collect your email address and a hashed password. We do
            not store plaintext passwords. If you connect a Riot Games account, we store the public
            identifiers associated with that account (game name, tag, PUUID, summoner ID) as
            provided by the Riot Games API.
          </p>
          <p className="mt-3">
            We collect usage data (pages visited, features used) to improve the product. This data
            is not sold or shared with third parties for advertising purposes.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-semibold text-text">Riot Account Data</h2>
          <p>
            LoL AI Coach uses the Riot Games API to retrieve your match history, ranked standing,
            and champion statistics. This data is fetched on your request and stored to power your
            coaching reports and dashboard. We only access data that is publicly available through
            the Riot Games API.
          </p>
          <p className="mt-3">
            You can disconnect your Riot account at any time from Settings. Disconnecting removes
            the link between your LoL AI Coach account and your Riot account. Your historical match
            data may be retained for service continuity unless you request deletion.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-semibold text-text">Usage Analytics</h2>
          <p>
            We may use privacy-respecting analytics tools (such as Vercel Analytics) to understand
            how users interact with the product. These tools do not use cookies and do not track you
            across other websites.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-semibold text-text">
            AI Generated Reports
          </h2>
          <p>
            Coaching reports are generated by sending anonymized match statistics to a third-party
            AI provider (OpenAI or Anthropic). Your personal identifiers (name, email, Riot
            username) are never included in prompts sent to AI providers. Generated reports are
            stored in our database and associated with your account.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-semibold text-text">Data Retention</h2>
          <p>
            We retain your account data for as long as your account is active. If you delete your
            account, your personal data is removed within 30 days. Match data sourced from the Riot
            API may be retained in anonymized form for aggregate analytics.
          </p>
          <p className="mt-3">To request data deletion, contact us at the email below.</p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-semibold text-text">Contact</h2>
          <p>
            If you have questions about this Privacy Policy or want to exercise your data rights,
            please contact us at{" "}
            <a
              href="mailto:privacy@lolaicoach.gg"
              className="text-accent underline underline-offset-2 hover:opacity-80"
            >
              privacy@lolaicoach.gg
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
